version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - medpredict-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - medpredict-network
    environment:
      - REACT_APP_BACKEND_URL=http://127.0.0.1:8000

networks:
  medpredict-network:
    external: true